import AppKit
import Defaults
import ImageIO
import Sauce
import UniformTypeIdentifiers

/// Pasteboard watcher. Polls NSPasteboard every `clipboardCheckInterval`, builds
/// a HistoryItem from each new copy, and fires registered hooks so History can
/// insert them. Also exposes copy(_:) for putting items back on the pasteboard.
class Clipboard {
  static let shared = Clipboard()

  typealias OnNewCopyHook = (HistoryItem) -> Void

  private var onNewCopyHooks: [OnNewCopyHook] = []
  /// Last seen `NSPasteboard.changeCount` — used to detect new copies cheaply.
  var changeCount: Int

  private let pasteboard = NSPasteboard.general

  private var timer: Timer?

  private let dynamicTypePrefix = "dyn."
  private let microsoftSourcePrefix = "com.microsoft.ole.source."
  private let supportedTypes: Set<NSPasteboard.PasteboardType> = [
    .fileURL,
    .html,
    .png,
    .rtf,
    .string,
    .tiff
  ]
  private let ignoredTypes: Set<NSPasteboard.PasteboardType> = [
    .autoGenerated,
    .concealed,
    .transient
  ]

  private var enabledTypes: Set<NSPasteboard.PasteboardType> { Defaults[.enabledPasteboardTypes] }
  private var disabledTypes: Set<NSPasteboard.PasteboardType> { supportedTypes.subtracting(enabledTypes) }

  private var sourceApp: NSRunningApplication? { NSWorkspace.shared.frontmostApplication }

  init() {
    changeCount = pasteboard.changeCount
  }

  /// Registers a callback invoked every time a new clip is detected on the pasteboard.
  func onNewCopy(_ hook: @escaping OnNewCopyHook) {
    onNewCopyHooks.append(hook)
  }

  /// Removes all registered onNewCopy hooks.
  func clearHooks() {
    onNewCopyHooks = []
  }

  /// Begins polling the pasteboard at the user-configured interval.
  func start() {
    timer = Timer.scheduledTimer(
      timeInterval: Defaults[.clipboardCheckInterval],
      target: self,
      selector: #selector(checkForChangesInPasteboard),
      userInfo: nil,
      repeats: true
    )
  }

  /// Re-creates the polling timer (use after the interval default changes).
  func restart() {
    timer?.invalidate()
    start()
  }

  /// Writes a plain string to the system pasteboard, then immediately checks for changes.
  @MainActor
  func copy(_ string: String) {
    pasteboard.clearContents()
    pasteboard.setString(string, forType: .string)
    sync()
    checkForChangesInPasteboard()
  }

  /// Writes a history item back to the system pasteboard. With `removeFormatting`,
  /// strips rich-text content and keeps only plain text + file URLs.
  @MainActor
  func copy(_ item: HistoryItem?, removeFormatting: Bool = false) {
    guard let item else { return }

    pasteboard.clearContents()
    var contents = item.contents

    if removeFormatting {
      contents = clearFormatting(contents)
    }

    for content in contents {
      guard content.type != NSPasteboard.PasteboardType.fileURL.rawValue else { continue }
      // Internal thumbnail — don't pollute paste targets with it.
      guard content.type != NSPasteboard.PasteboardType.osToolbarThumbnail.rawValue else { continue }
      pasteboard.setData(content.value, forType: NSPasteboard.PasteboardType(content.type))
    }

    // Use writeObjects for file URLs so that multiple files that are copied actually work.
    // Only do this for file URLs because it causes an issue with some other data types (like formatted text)
    // where the item is pasted more than once.
    let fileURLItems: [NSPasteboardItem] = contents.compactMap { item in
      guard item.type == NSPasteboard.PasteboardType.fileURL.rawValue else { return nil }
      guard let value = item.value else { return nil }
      let pasteItem = NSPasteboardItem()
      pasteItem.setData(value, forType: NSPasteboard.PasteboardType(item.type))
      return pasteItem
    }
    pasteboard.writeObjects(fileURLItems)

    pasteboard.setString("", forType: .fromOSToolbar)
    pasteboard.setString(item.application ?? "", forType: .source)
    sync()

    Task {
      Notifier.notify(body: item.title, sound: .knock)
      checkForChangesInPasteboard()
    }
  }

  /// Intentional no-op — OSToolbar never sends ⌘V to other apps.
  /// Avoids needing the macOS Accessibility permission entirely.
  func paste() {}

  // 2× display size (340 pt) — crisp on Retina without storing MBs.
  private static let thumbnailMaxPixel: CGFloat = 680
  private static let thumbnailQuality: CGFloat = 0.6

  private static let imageTypeRawValues: Set<String> = [
    NSPasteboard.PasteboardType.tiff.rawValue,
    NSPasteboard.PasteboardType.png.rawValue,
    NSPasteboard.PasteboardType.jpeg.rawValue,
    NSPasteboard.PasteboardType.heic.rawValue
  ]

  private static func imageBytes(in contents: [HistoryItemContent]) -> Data? {
    contents.first(where: { imageTypeRawValues.contains($0.type) })?.value
  }

  // Background-encodes the thumbnail and attaches it back on the main actor.
  private static func attachThumbnailAsync(to historyItem: HistoryItem, from imageBytes: Data) {
    Task.detached(priority: .utility) {
      guard let jpeg = downsampledJPEG(from: imageBytes,
                                       maxPixel: thumbnailMaxPixel,
                                       quality: thumbnailQuality) else { return }
      await MainActor.run {
        let thumb = HistoryItemContent(
          type: NSPasteboard.PasteboardType.osToolbarThumbnail.rawValue,
          value: jpeg
        )
        thumb.item = historyItem
        historyItem.contents.append(thumb)
        // Decorator's first .onAppear ran before attach completed; nudge it.
        History.shared.all.first(where: { $0.item === historyItem })?.ensureThumbnailImage()
      }
    }
  }

  // HTML-only web copies: extract first inline base64 <img>, decode, feed
  // through the same pipeline. Regex + base64 + downsample all off-main.
  private static func attachThumbnailFromHTMLAsync(to historyItem: HistoryItem, htmlBytes: Data) {
    Task.detached(priority: .utility) {
      guard let html = String(data: htmlBytes, encoding: .utf8)
              ?? String(data: htmlBytes, encoding: .utf16)
              ?? String(data: htmlBytes, encoding: .isoLatin1) else { return }
      let pattern = #"<img[^>]*\bsrc=["']data:image/[^;]+;base64,([^"']+)["']"#
      guard let regex = try? NSRegularExpression(pattern: pattern,
                                                 options: [.caseInsensitive, .dotMatchesLineSeparators]),
            let match = regex.firstMatch(in: html, options: [],
                                         range: NSRange(html.startIndex..., in: html)),
            match.numberOfRanges >= 2,
            let range = Range(match.range(at: 1), in: html),
            let imageBytes = Data(base64Encoded: String(html[range]),
                                  options: .ignoreUnknownCharacters) else { return }
      guard let jpeg = downsampledJPEG(from: imageBytes,
                                       maxPixel: thumbnailMaxPixel,
                                       quality: thumbnailQuality) else { return }
      await MainActor.run {
        let thumb = HistoryItemContent(
          type: NSPasteboard.PasteboardType.osToolbarThumbnail.rawValue,
          value: jpeg
        )
        thumb.item = historyItem
        historyItem.contents.append(thumb)
        History.shared.all.first(where: { $0.item === historyItem })?.ensureThumbnailImage()
      }
    }
  }

  // ImageIO downscale → JPEG re-encode. Reads only what's needed for the target size.
  private static func downsampledJPEG(from data: Data, maxPixel: CGFloat, quality: CGFloat) -> Data? {
    guard let source = CGImageSourceCreateWithData(data as CFData, nil) else { return nil }
    let opts: [CFString: Any] = [
      kCGImageSourceCreateThumbnailFromImageAlways: true,
      kCGImageSourceCreateThumbnailWithTransform: true,
      kCGImageSourceShouldCacheImmediately: true,
      kCGImageSourceThumbnailMaxPixelSize: maxPixel
    ]
    guard let cgImage = CGImageSourceCreateThumbnailAtIndex(source, 0, opts as CFDictionary) else {
      return nil
    }
    let out = NSMutableData()
    guard let dest = CGImageDestinationCreateWithData(out, UTType.jpeg.identifier as CFString, 1, nil) else {
      return nil
    }
    CGImageDestinationAddImage(dest, cgImage, [kCGImageDestinationLossyCompressionQuality: quality] as CFDictionary)
    return CGImageDestinationFinalize(dest) ? (out as Data) : nil
  }

  /// Clears the system pasteboard if the user has opted in via Defaults.
  func clear() {
    guard Defaults[.clearSystemClipboard] else {
      return
    }

    pasteboard.clearContents()
  }

  /// Polling tick: detects new pasteboard contents, builds a HistoryItem, and
  /// invokes onNewCopy hooks. Skips when the change came from our own copy(),
  /// the source app is ignored, or the user has paused history capture.
  @objc
  @MainActor
  func checkForChangesInPasteboard() { // swiftlint:disable:this cyclomatic_complexity
    guard pasteboard.changeCount != changeCount else {
      return
    }

    changeCount = pasteboard.changeCount

    if pasteboard.pasteboardItems?.contains(where: { $0.types.contains(.fromOSToolbar) }) != true {
      // External copy occurred. Stop the current paste stack.
      // Maybe queue it into the paste stack? Configurable behaviour?
      AppState.shared.history.interruptPasteStack()
    }

    if Defaults[.ignoreEvents] {
      if Defaults[.ignoreOnlyNextEvent] {
        Defaults[.ignoreEvents] = false
        Defaults[.ignoreOnlyNextEvent] = false
      }

      return
    }

    // Reading types on NSPasteboard gives all the available
    // types - even the ones that are not present on the NSPasteboardItem.
    if shouldIgnore(Set(pasteboard.types ?? [])) {
      return
    }

    if let sourceAppBundle = sourceApp?.bundleIdentifier, shouldIgnore(sourceAppBundle) {
      return
    }

    // Some applications (BBEdit, Edge) add 2 items to pasteboard when copying
    // so it's better to merge all data into a single record.
    var contents = [HistoryItemContent]()
    pasteboard.pasteboardItems?.forEach({ item in
      var types = Set(item.types)
      if types.contains(.string) && isEmptyString(item) && !richText(item) {
        return
      }

      if shouldIgnore(item) {
        return
      }

      types = types
        .subtracting(disabledTypes)
        .filter { !$0.rawValue.starts(with: dynamicTypePrefix) }
        .filter { !$0.rawValue.starts(with: microsoftSourcePrefix) }

      // Avoid reading Microsoft Word links from bookmarks and cross-references.
      if types.isSuperset(of: [.microsoftLinkSource, .microsoftObjectLink]) {
        types = types.subtracting([.microsoftLinkSource, .microsoftObjectLink, .pdf])
      }

      types.forEach { type in
        contents.append(HistoryItemContent(type: type.rawValue, value: item.data(forType: type)))
      }
    })

    guard !contents.isEmpty else {
      return
    }

    // Image bytes for background thumbnail gen — direct first, HTML inline as fallback.
    let imageBytesForThumbnail = Self.imageBytes(in: contents)
    let htmlBytesForImageFallback: Data? = (imageBytesForThumbnail == nil)
      ? contents.first(where: { $0.type == NSPasteboard.PasteboardType.html.rawValue })?.value
      : nil

    let historyItem = HistoryItem(contents: contents)

    if #unavailable(macOS 15.0) {
      // macOS 14: insert before the hook runs.
      try? History.shared.insertIntoStorage(historyItem)
    }

    historyItem.application = sourceApp?.bundleIdentifier
    historyItem.title = historyItem.generateTitle()

    onNewCopyHooks.forEach({ $0(historyItem) })

    if let imageBytes = imageBytesForThumbnail {
      Self.attachThumbnailAsync(to: historyItem, from: imageBytes)
    } else if let html = htmlBytesForImageFallback {
      Self.attachThumbnailFromHTMLAsync(to: historyItem, htmlBytes: html)
    }
  }

  private func shouldIgnore(_ types: Set<NSPasteboard.PasteboardType>) -> Bool {
    let ignoredTypes = self.ignoredTypes
      .union(Defaults[.ignoredPasteboardTypes].map({ NSPasteboard.PasteboardType($0) }))

    return types.isDisjoint(with: enabledTypes) ||
      !types.isDisjoint(with: ignoredTypes)
  }

  private func shouldIgnore(_ sourceAppBundle: String) -> Bool {
    if Defaults[.ignoreAllAppsExceptListed] {
      return !Defaults[.ignoredApps].contains(sourceAppBundle)
    } else {
      return Defaults[.ignoredApps].contains(sourceAppBundle)
    }
  }

  private func shouldIgnore(_ item: NSPasteboardItem) -> Bool {
    for regexp in Defaults[.ignoreRegexp] {
      if let string = item.string(forType: .string) {
        do {
          let regex = try NSRegularExpression(pattern: regexp)
          if regex.numberOfMatches(in: string, range: NSRange(string.startIndex..., in: string)) > 0 {
            return true
          }
        } catch {
          return false
        }
      }
    }
    return false
  }

  private func isEmptyString(_ item: NSPasteboardItem) -> Bool {
    guard let string = item.string(forType: .string) else {
      return true
    }

    return string.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
  }

  private func richText(_ item: NSPasteboardItem) -> Bool {
    if let rtf = item.data(forType: .rtf) {
      if let attributedString = NSAttributedString(rtf: rtf, documentAttributes: nil) {
        return !attributedString.string.isEmpty
      }
    }

    if let html = item.data(forType: .html) {
      if let attributedString = NSAttributedString(html: html, documentAttributes: nil) {
        return !attributedString.string.isEmpty
      }
    }

    return false
  }

  // Some applications requires window be unfocused and focused back to sync the clipboard.
  // - Chrome Remote Desktop
  // - Netbeans
  private func sync() {
    guard let app = sourceApp,
          app.bundleURL?.lastPathComponent == "Chrome Remote Desktop.app" ||
            app.localizedName?.contains("NetBeans") == true else {
      return
    }

    NSApp.activate(ignoringOtherApps: true)
    NSApp.hide(self)
  }

  private func clearFormatting(_ contents: [HistoryItemContent]) -> [HistoryItemContent] {
    var newContents: [HistoryItemContent] = contents
    let stringContents = contents.filter { NSPasteboard.PasteboardType($0.type) == .string }

    // If there is no string representation of data,
    // behave like we didn't have to remove formatting.
    if !stringContents.isEmpty {
      newContents = stringContents

      // Preserve file URLs.
      let fileURLContents = contents.filter { NSPasteboard.PasteboardType($0.type) == .fileURL }
      if !fileURLContents.isEmpty {
        newContents += fileURLContents
      }
    }

    return newContents
  }

}
